config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get '/signup' => 'users#new', as: :signup
  post '/users' => 'users#create', as: :users
  get '/users/:id' => 'users#show', as: :user

  get 'links' => 'links#index', as: :links

  get '/login' =>  'session#new', as: :login
  post 'auth' => 'session#create', as: :auth
  get '/logout' => 'session#destroy', as: :logout

  get 'posts/new' => 'posts#new', as: :new_post
  post 'posts' => 'posts#create', as: :posts
  get 'posts/:id' => 'posts#show', as: :post
  get 'posts/:id/downvote' => 'posts#downvote', as: :downvote_post
  get 'posts/:id/edit' => 'posts#edit', as: :edit_post
  get 'posts/:id/upvote' => 'posts#upvote', as: :upvote
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#delete'

resources :users

end

app/models/link.rb
class Link < ActiveRecord::Base

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

  validates :link, presence: true
  validates :title, presence: true



end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_secure_password
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,  format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all.order("votes desc")
    render :index
  end
  def new
    @post = Post.new
  end

  def edit
    @post = Post.find params[:id]
  end

  def create
    @post = Post.new params.require(:post).permit(:title, :link, :user_id)
      if @post.save
        redirect_to root_path
      else
        render :new
      end
  end

  def show
    @post = Post.find params[:id]
  end

  def downvote
  @post = Post.find params[:id]
  @post.votes -= 1
  @post.save
  redirect_to root_path
  end

  def upvote
  @post = Post.find params[:id]
  @post.votes += 1
  @post.save
  redirect_to root_path
  end


  def update
    @post = Post.find params[:id]
      if @post.update params.require(:post).permit(:title, :link, :votes, :vote_down, :user_id)
        redirect_to root_path
      else
        render :edit
      end
  end

  def delete
    @post = Post.find params[:id]
    @post.destroy
    redirect_to root_path
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    name = params[:name]
    password = params[:password]

    user = User.find_by name: name
    if (user) && (user.authenticate password)
      session[:user_id] = user.id
      redirect_to user
    else
      flash.now[:danger] = "Try again. Invalid email/password combination"
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action do
    @user_id = session[:user_id]
    @current_user = User.find_by id: @user_id
    @posts = Post.all.order("votes desc" )
      # if @current_user.nil?
      #   redirect_to login_path
      # end
    end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:name, :password, :email, :password_confirmation, :id)
    if @user.save
      flash[:success] = "Welcome to Reddit"
      redirect_to @user
    else
      render :new
    end
  end


  def show
    @user = User.find(params[:id])
    @users = User.all
    @posts = Post.all.order("votes desc")
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="nav">
  <nav class="navbar navbar-inverse">
    <% if @current_user.nil? %>
    <p> <%= link_to "Log In", login_path %> </p>
    <% else %>
    <p> <%= link_to "Log Out", logout_path %> </p>
    <!-- <p> link_to "Home", user_path(id: user.id)  </p> -->
    <%end%>
    <p>
  </nav>
</div>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for @post do |f| %>
        <div class="label">
          <h3> Title</h3>
          <%= f.text_field :title, class: "form-control" %>
          <h3> Link</h3>
          <%= f.text_field :link, class: "form-control" %>
            <div class="btn-signin">
              <%= f.submit class: "btn btn-primary" %>
            </div>
        </div>
    </div>
  </div>
    <%end%>
</div>

app/views/posts/edit.html.erb
<%= render partial: 'form' %>

app/views/posts/index.html.erb
<div class="container">

  <h1> Reddit </h1>
  <h4> Where would you like to escape to today? </h4>

  <% @posts.each do |post| %>
  <div class="well col-md-8 ">

          <a  <span class="glyphicon glyphicon-arrow-up "  <%= link_to "", upvote_path(id: post.id)%>  </span> </a>
              <%= post.votes %>
          <a <span class="glyphicon glyphicon-arrow-down" <%= link_to "", downvote_post_path(id: post.id)%></a>

            <%= link_to post.title, (post.link)  %>
            <p> <em>Posted:</em> <%=distance_of_time_in_words_to_now post.created_at %> </p>
    </div>
    <% end %>
    <br>

</div>

app/views/posts/new.html.erb
<%= render partial: 'form' %>

app/views/session/new.html.erb
<div class="col-md-8 col-md-offset-2" >
<div class="jumbotron">
    <h1> Welcome to Reddit </h1>


    <%= form_tag auth_path, method: :post do %>
      <div class="label">
        <%= label_tag :name %>
        <%= text_field_tag :name, "", class: "form-control" %>
      <br>
      </div>

      <div class="label">
        <%= label_tag :email %>
        <%= text_field_tag :email, "", class: "form-control" %>
      <br>
      </div>

    <div class="label">
      <%= label_tag :password %>
      <%= password_field_tag :password, "", class: "form-control" %>
    <br>
    </div>

      <div>
        <%= submit_tag "Log In", class: "btn btn-primary btn-lg btn-signin" %>
      <br>
      <br>
      </div>

      <%end%>

      <p> Still don't have an account? <%= link_to 'Sign up now', signup_path %> </p>
</div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container">

  <div class=" center jumbotron">
    <h1>Go ahead and sign up</h1>


  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for @user do |f| %>
        <div class="label">
          <%= f.input :name %>
          <br>
          <%= f.input :email %>
          <br>
          <%= f.input :password %>
          <br>
          <%= f.input :password_confirmation, label: 'Confirm Password' %>
          <br>
      </div>
      <div class="btn-signin">
        <%= f.button :submit  %>
      </div>
      <% end %>
      <br>
      <br>
</div>
</div>
<div>
</div>

app/views/users/show.html.erb
<div class="container">

    <h4>Where would you like to escape to today?</h4>
    <p><a class="btn btn-primary btn-lg btn-signin"<%= link_to 'Add a new getaway', new_post_path %></p> </a>


  <h1> Reddit </h1>

  <% @posts.each do |post| %>
  <div class="well">
          <a  <span class="glyphicon glyphicon-arrow-up "  <%= link_to "", upvote_path(id: post.id)%> </span> </a>
              <%= post.votes %>
          <a <span class="glyphicon glyphicon-arrow-down" <%= link_to "", downvote_post_path(id: post.id)%></a>
            <%= link_to post.title, (post.link)  %>
            <p> <em>Posted:</em> <%=distance_of_time_in_words_to_now post.created_at %> </p>
            

          <!-- <a class="btn btn-primary btn-sm" <%= link_to 'Edit', edit_post_path(id: post.id)%></a>
          <a class="btn btn-primary btn-sm" <%= link_to 'Delete', post_path(id: post.id), method: 'delete', data: {confirm: 'Are you sure you want to delete this post?'}%></a> -->

    </div>
    <% end %>

</div>